from pyinfra import local

local.include("tasks/bootstrap.py")
local.include("tasks/hardening.py")
local.include("tasks/network_restrict.py")
local.include("tasks/secrets_files.py")
local.include("tasks/cloudflare_dns.py")
local.include("tasks/unbound.py")
local.include("tasks/pihole.py")
local.include("tasks/wireguard.py")
local.include("tasks/wg_portal.py")
local.include("tasks/traefik.py")
local.include("tasks/cifs.py")
local.include("tasks/podman.py")
local.include("tasks/hcc.py")
local.include("tasks/audiobookshelf.py")
local.include("tasks/navidrome.py")
local.include("tasks/ntfy.py")
local.include("tasks/gatus.py")
local.include("tasks/trivy.py")
local.include("tasks/ddns.py")
local.include("tasks/vaultwarden.py")
local.include("tasks/yarr.py")
local.include("tasks/syncthing.py")
local.include("tasks/vuio.py")
local.include("tasks/network_monitor.py")
