"""
Bitwarden CLI helpers. Requires BW_SESSION env var to be set:
    set -x BW_SESSION (bw unlock --raw)

Item structure in the 'raspi' folder:
  cloudflare        login  password=api_token  fields: zone_id
  cifs              login  (unused)            fields: {share}_username, {share}_password (hidden) per CIFS key
                                               (e.g. backups_username/password for the restic repo share)
  audiobookshelf    login  username/password   fields: api_key (hidden)
  wireguard-portal  login  username/password   fields: api_token
  wireguard-server-key     (no login)          fields: private_key (hidden), public_key
  asus-router              SSH key item        (uses Bitwarden SSH key type)
  hcc               login  (unused)            fields: one hidden field per HCC["secret_env"]
                                               value in group_data/all.py (e.g. tomorrow_io_api_key,
                                               solis_key_id, solis_key_secret, hue_bridge_user)
  pihole            login  password=admin_password
  dockerhub         login  username/password   (personal access token from hub.docker.com/settings/security)
  vaultwarden       login  password=admin_password (plain text, for logging in)
                           fields: admin_token (hidden, argon2 hash; generate with:
                             docker run --rm -it vaultwarden/server /vaultwarden hash --preset owasp)
                                   smtp_email   (Gmail address used for SMTP_USERNAME and SMTP_FROM)
                                   smtp_password (hidden, Gmail app password)
  yarr              login  username/password   (use alphanumeric-only password — no colons)
  navidrome         login  username/password   (only required when oauth2-proxy is
                                                NOT configured — used to bootstrap
                                                an admin user for native Subsonic auth)
  memos             login  username/password   (bootstrap HOST/admin user — first POST
                                                /api/v1/users assigns HOST role; kept as
                                                fallback for non-SSO admin login)
  syncthing         login  username/password   (web UI credentials)
  beszel            login  email/password       (email stored as username; used to bootstrap
                                               hub admin + superuser). USER_EMAIL/PASSWORD seed
                                               the hub UI user on first boot (write-once);
                                               `beszel superuser upsert` runs every deploy to
                                               keep the PocketBase admin panel login in sync.
                                               The agent universal token is fetched from the hub
                                               API at deploy time — no Bitwarden field needed.
  kanidm            login  (unused)             fields: admin_password (hidden, generated by
                                                 `kanidmd recover-account admin` on first deploy);
                                               idm_admin_password (hidden, generated by
                                                 `kanidmd recover-account idm_admin`);
                                               one `{client}_client_secret` (hidden) per OIDC client
                                                 (generated by Kanidm, read from API, saved to BW);
                                               one `{username}_reset_token` (hidden) per person
                                                 (credential reset URL, saved on first deploy)
  oauth2-proxy      login  (unused)             fields: cookie_secret (hidden, base64-encoded 32
                                                 random bytes; generated locally on first deploy
                                                 and persisted so sessions survive restarts)
  chat              login  (unused)             fields: session_key (hidden, 64-byte hex; generated
                                                 locally on first deploy and persisted so SSE/auth
                                                 sessions survive restarts)
  restic            login  password=repo_password (used to encrypt the restic backup repo;
                                                  treat as load-bearing — losing this means
                                                  losing access to all snapshots)
"""

import base64
import functools
import json
import secrets
import subprocess


def _bw(*args):
    result = subprocess.run(
        ["bw"] + list(args),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


@functools.cache
def _folder_id():
    folders = json.loads(_bw("list", "folders"))
    match = next((f for f in folders if f["name"] == "raspi"), None)
    if not match:
        raise RuntimeError(
            "Bitwarden folder 'raspi' not found.\n"
            'Run: bw create folder (echo \'{"name":"raspi"}\' | bw encode)'
        )
    return match["id"]


def _edit_item(item):
    """Encode and save an item to Bitwarden, then clear the cache."""
    encoded = subprocess.run(
        ["bw", "encode"],
        input=json.dumps(item),
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    subprocess.run(
        ["bw", "edit", "item", item["id"], encoded],
        capture_output=True,
        text=True,
        check=True,
    )
    _get_item.cache_clear()


@functools.cache
def _get_item(name):
    items = json.loads(_bw("list", "items", "--search", name, "--folderid", _folder_id()))
    matches = [i for i in items if i["name"] == name]
    if not matches:
        raise RuntimeError(f"Bitwarden item 'raspi/{name}' not found")
    return matches[0]


def _fields(item_name) -> dict:
    item = _get_item(item_name)
    return {f["name"]: f["value"] for f in (item.get("fields") or [])}


def bw_field(item: str, field: str) -> str:
    """Return a single hidden/text field from a Bitwarden item, or empty string.

    Used by tasks that map a service env var name to a BW field name via the
    `secret_env` dict in `group_data/all.py` (see HCC for the canonical example).
    """
    return _fields(item).get(field, "") or ""


def pihole_password() -> str:
    return _get_item("pihole")["login"]["password"]


def cifs_creds(share_name: str) -> str:
    f = _fields("cifs")
    return f"username={f[f'{share_name}_username']}\npassword={f[f'{share_name}_password']}\n"


def abs_creds() -> dict:
    login = _get_item("audiobookshelf")["login"]
    return {"username": login["username"], "password": login["password"]}


def abs_api_key() -> str:
    """Return the current ABS API key stored in Bitwarden, or empty string."""
    return _fields("audiobookshelf").get("api_key", "") or ""


def save_abs_api_key(token: str) -> None:
    """Write the ABS user API token to the api_key hidden field."""
    item = json.loads(json.dumps(_get_item("audiobookshelf")))  # copy
    fields = item.get("fields") or []
    existing = next((f for f in fields if f["name"] == "api_key"), None)
    if existing:
        existing["value"] = token
    else:
        fields.append({"name": "api_key", "value": token, "type": 1})
    item["fields"] = fields
    _edit_item(item)


def wg_portal_creds() -> dict:
    item = _get_item("wireguard-portal")
    return {
        "username": item["login"]["username"],
        "password": item["login"]["password"],
        "api_token": _fields("wireguard-portal").get("api_token", ""),
    }


def cloudflare() -> dict:
    item = _get_item("cloudflare")
    return {
        "token": item["login"]["password"],
        "zone_id": _fields("cloudflare")["zone_id"],
    }


def wg_server_key() -> dict:
    f = _fields("wireguard-server-key")
    return {k: v for k, v in f.items() if v}


def vaultwarden_admin_token_hash() -> str:
    return _fields("vaultwarden")["admin_token"]


def vaultwarden_smtp_email() -> str:
    return _fields("vaultwarden")["smtp_email"]


def vaultwarden_smtp_password() -> str:
    return _fields("vaultwarden")["smtp_password"]


def asus_router_ssh() -> dict:
    item = _get_item("asus-router")
    ssh = item["sshKey"]
    return {"private_key": ssh["privateKey"], "public_key": ssh["publicKey"]}


def yarr_creds() -> dict:
    login = _get_item("yarr")["login"]
    return {"username": login["username"], "password": login["password"]}


def navidrome_creds() -> dict:
    login = _get_item("navidrome")["login"]
    return {"username": login["username"], "password": login["password"]}


def memos_creds() -> dict:
    login = _get_item("memos")["login"]
    return {"username": login["username"], "password": login["password"]}


def restic_password() -> str:
    return _get_item("restic")["login"]["password"]


def syncthing_creds() -> dict:
    login = _get_item("syncthing")["login"]
    return {"username": login["username"], "password": login["password"]}


def dockerhub_creds() -> dict:
    login = _get_item("dockerhub")["login"]
    return {"username": login["username"], "password": login["password"]}


def beszel_admin_creds() -> dict:
    """Hub admin email + password. Empty strings if item missing — hub will come
    up with no admin user, set one via the web UI, populate BW, then redeploy."""
    try:
        login = _get_item("beszel")["login"]
    except RuntimeError:
        return {"email": "", "password": ""}
    return {"email": login.get("username") or "", "password": login.get("password") or ""}


def kanidm_oidc_secret(field_name: str) -> str:
    """Return an OIDC client secret from the kanidm BW item, or empty string.

    Returns empty on first deploy before Kanidm has generated the secret."""
    return _fields("kanidm").get(field_name, "") or ""


def oauth2_proxy_cookie_secret() -> str:
    """Return the oauth2-proxy cookie secret, generating + persisting it on first call.

    A stable cookie secret is required so sessions survive restarts."""
    existing = _fields("oauth2-proxy").get("cookie_secret", "") or ""
    if existing:
        return existing
    new = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip("=")
    item = json.loads(json.dumps(_get_item("oauth2-proxy")))  # copy
    fields = item.get("fields") or []
    fields.append({"name": "cookie_secret", "value": new, "type": 1})
    item["fields"] = fields
    _edit_item(item)
    return new


def chat_session_key() -> str:
    """Return chat SESSION_KEY (64-byte hex), generating + persisting on first call.

    A stable key is required so cookie-encrypted sessions survive restarts."""
    existing = _fields("chat").get("session_key", "") or ""
    if existing:
        return existing
    new = secrets.token_hex(64)
    item = json.loads(json.dumps(_get_item("chat")))  # copy
    fields = item.get("fields") or []
    fields.append({"name": "session_key", "value": new, "type": 1})
    item["fields"] = fields
    _edit_item(item)
    return new


def save_wg_server_key(private_key: str, public_key: str) -> None:
    item = json.loads(json.dumps(_get_item("wireguard-server-key")))  # copy
    item["fields"] = [
        {"name": "private_key", "value": private_key, "type": 1},
        {"name": "public_key", "value": public_key, "type": 0},
    ]
    _edit_item(item)
