"""
Secret access for the deploy — backend-agnostic.

The deploy never hardwires a secret manager. A thin ``Backend`` (5 primitives:
read_login / read_field / read_ssh_key / write_field / item_exists) sits under a
stable set of public helpers (``cloudflare()``, ``restic_password()``, …) that
the task files call. Swapping vendors is a backend swap, not a task rewrite.

Selection (env):
  SECRET_BACKEND   op | bw          (default: op)
  OP_VAULT         vault/folder name (default: raspi)

Auth:
  op (default) — 1Password CLI via the desktop-app integration. The first `op`
    call in a deploy triggers Touch ID; the unlock is cached (~10 min) for the
    rest. No session env var. (Enable: 1Password → Settings → Developer →
    "Integrate with 1Password CLI". `op signin` if not using the desktop app.)
  bw (legacy) — Bitwarden CLI. Set BW_SESSION=(bw unlock --raw) before deploy.

Item / field map (one vault/folder, items named as below):
  cloudflare        login  password=api_token  field: zone_id
  cifs              login  (unused)            fields: readonly_username/readonly_password,
                                               readwrite_username/readwrite_password — the two
                                               shared NAS logins every CIFS share picks from
                                               via its `creds` key
  netbird           login  (unused)             fields: auth_secret (64-byte hex, auto),
                                               encryption_key (base64 of 32 bytes, auto),
                                               session_cookie_encryption_key (32-byte hex, auto),
                                               bootstrap_owner_password (auto — the one-time
                                                 /api/setup owner; NetBird owns it after that),
                                               pat (the API token reconcile authenticates
                                                 with, and rotates before its 365-day cap.
                                                 Seeded by /api/setup on a fresh server,
                                                 then replaced ONCE BY HAND with a token
                                                 minted in the dashboard by the Kanidm
                                                 user — see the "one manual step" section
                                                 in CLAUDE.md for why that is unavoidable),
                                               setup_key_<name> per NETBIRD["setup_keys"]
                                                 (server-generated, shown once)
  asus-router              SSH key item         private key (OpenSSH) + public key
  halo                     secure note         fields: one per HALO["secret_env"] in group_data/all.py
                                               (tomorrow_io_api_key, solis_key_id, solis_key_secret,
                                               hue_bridge_user)
  reserve                  login               username=email, password; field: api_base_url
                                               (reserve-market updater; via vault.reserve_creds())
  pihole            login  password=admin_password
  dockerhub         login  username/password   (PAT from hub.docker.com/settings/security)
  vaultwarden       login  password=admin_password (plain, for logging in)
                           fields: admin_token (argon2 hash; generate with:
                             docker run --rm -it vaultwarden/server /vaultwarden hash --preset owasp)
                                   smtp_email   (Gmail address — SMTP_USERNAME + SMTP_FROM)
                                   smtp_password (Gmail app password)
  yarr              login  username/password   (alphanumeric-only password — no colons)
  navidrome         login  username/password   (only when oauth2-proxy is NOT configured —
                                                bootstraps an admin for native Subsonic auth)
  memos             login  username/password   (bootstrap HOST/admin — first POST /api/v1/users
                                                assigns HOST role; non-SSO admin fallback)
  syncthing         login  username/password   (web UI credentials)
  beszel            login  email/password       (email in username; bootstraps hub admin + superuser).
                           fields: user_pw_<email> — auto-generated per managed user
                                   (BESZEL["users"]). NOTE: 1Password splits the email's dot,
                                   so this lands as section `user_pw_<local@host>` / field `com`;
                                   read_field matches the reconstructed `section.label` form.
  kanidm            login  (unused)             fields: admin_password, idm_admin_password
                                                 (generated by `kanidmd recover-account`);
                                               {client}_client_secret per OIDC client (from Kanidm API);
                                               {username}_reset_token per person (first deploy)
  oauth2-proxy      login  (unused)             field: cookie_secret (base64 32 random bytes;
                                                 generated locally on first deploy, persisted)
  chat              login  (unused)             fields: session_key (64-byte hex), mcp_api_key (32),
                                               mcp_server_key (32) — all auto-generated, persisted
  represent         login  (unused)             field: session_key (64-byte hex, auto)
  scribe            login  (unused)             fields: session_key (64-byte hex, auto),
                                               press_token (hand-pasted; must match the mini's
                                                 `mini/scribe-press` api_key field),
                                               shim_passphrase (48-byte hex, auto),
                                               shelf_api_key (32-byte hex, auto — shared with shelf.env)
  restic            login  password=repo_password (encrypts the restic repo — load-bearing,
                                                  losing it loses all snapshots)
"""

import base64
import json
import os
import secrets
import subprocess
from typing import Protocol


class Backend(Protocol):
    """Vendor-neutral secret store. All reads return "" for a missing field so
    optional/first-deploy paths stay branch-free."""

    def read_login(self, item: str) -> dict: ...
    def read_field(self, item: str, field: str) -> str: ...
    def read_ssh_key(self, item: str) -> dict: ...
    def write_field(self, item: str, field: str, value: str, concealed: bool = True) -> None: ...
    def item_exists(self, item: str) -> bool: ...


# --------------------------------------------------------------------------- #
# 1Password backend (default)
# --------------------------------------------------------------------------- #


class OpBackend:
    """1Password CLI. Reads parse `op item get --format json` (robust to
    sectioned fields, unlike `op read op://…`); the SSH private key is the one
    value `op read` must fetch (the JSON value is empty for SSHKEY fields).
    Writes use `op item edit item 'label[password|text]=value'`."""

    def __init__(self, vault: str):
        self.vault = vault
        self._cache: dict[str, dict] = {}

    def _op(self, *args: str) -> str:
        return subprocess.run(
            ["op", *args, "--vault", self.vault],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()

    def _item(self, name: str) -> dict:
        if name not in self._cache:
            self._cache[name] = json.loads(self._op("item", "get", name, "--format", "json"))
        return self._cache[name]

    def _field_map(self, name: str) -> dict:
        """label -> value for flat fields; for sectioned fields the key is the
        reconstructed `section.label` (recovers names 1Password split on a dot,
        e.g. the beszel `user_pw_<email>` fields)."""
        out: dict[str, str] = {}
        for f in self._item(name).get("fields", []):
            val = f.get("value")
            if val is None:
                continue
            label = f.get("label", "")
            section = (f.get("section") or {}).get("label")
            out[f"{section}.{label}" if section else label] = val
        return out

    def read_login(self, item: str) -> dict:
        login = {"username": "", "password": ""}
        for f in self._item(item).get("fields", []):
            if f.get("purpose") == "USERNAME":
                login["username"] = f.get("value") or ""
            elif f.get("purpose") == "PASSWORD":
                login["password"] = f.get("value") or ""
        return login

    def read_field(self, item: str, field: str) -> str:
        return self._field_map(item).get(field, "") or ""

    def read_ssh_key(self, item: str) -> dict:
        # `op read` takes the vault in the op:// URI, not a --vault flag.
        private = subprocess.run(
            ["op", "read", f"op://{self.vault}/{item}/private key?ssh-format=openssh"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        return {"private_key": private, "public_key": self.read_field(item, "public key")}

    def write_field(self, item: str, field: str, value: str, concealed: bool = True) -> None:
        # NOTE: the value is an argv element (briefly visible in the local
        # process table) — acceptable for a single-user control host; it never
        # enters the deploy transcript. `password` -> concealed field, `text` -> plain.
        self._op("item", "edit", item, f"{field}[{'password' if concealed else 'text'}]={value}")
        self._cache.pop(item, None)

    def item_exists(self, item: str) -> bool:
        try:
            self._item(item)
            return True
        except subprocess.CalledProcessError:
            return False


# --------------------------------------------------------------------------- #
# Bitwarden backend (legacy fallback — SECRET_BACKEND=bw)
# --------------------------------------------------------------------------- #


class BwBackend:
    """Bitwarden CLI. Requires BW_SESSION. Kept as a working fallback during the
    1Password migration; revisit if it starts to drift from OpBackend."""

    def __init__(self, folder: str):
        self.folder = folder
        self._folder_id_cache: str | None = None
        self._item_cache: dict[str, dict] = {}

    def _bw(self, *args: str) -> str:
        return subprocess.run(
            ["bw", *args], capture_output=True, text=True, check=True
        ).stdout.strip()

    def _folder_id(self) -> str:
        if self._folder_id_cache is None:
            folders = json.loads(self._bw("list", "folders"))
            match = next((f for f in folders if f["name"] == self.folder), None)
            if not match:
                raise RuntimeError(
                    f"Bitwarden folder '{self.folder}' not found.\n"
                    'Run: bw create folder (echo \'{"name":"raspi"}\' | bw encode)'
                )
            self._folder_id_cache = match["id"]
        return self._folder_id_cache

    def _item(self, name: str) -> dict:
        if name not in self._item_cache:
            items = json.loads(
                self._bw("list", "items", "--search", name, "--folderid", self._folder_id())
            )
            matches = [i for i in items if i["name"] == name]
            if not matches:
                raise RuntimeError(f"Bitwarden item '{self.folder}/{name}' not found")
            self._item_cache[name] = matches[0]
        return self._item_cache[name]

    def read_login(self, item: str) -> dict:
        login = self._item(item).get("login") or {}
        return {"username": login.get("username") or "", "password": login.get("password") or ""}

    def read_field(self, item: str, field: str) -> str:
        fields = {f["name"]: f["value"] for f in (self._item(item).get("fields") or [])}
        return fields.get(field, "") or ""

    def read_ssh_key(self, item: str) -> dict:
        ssh = self._item(item)["sshKey"]
        return {"private_key": ssh["privateKey"], "public_key": ssh["publicKey"]}

    def write_field(self, item: str, field: str, value: str, concealed: bool = True) -> None:
        data = json.loads(json.dumps(self._item(item)))  # deep copy
        fields = data.get("fields") or []
        existing = next((f for f in fields if f["name"] == field), None)
        if existing:
            existing["value"] = value
        else:
            fields.append({"name": field, "value": value, "type": 1 if concealed else 0})
        data["fields"] = fields
        encoded = subprocess.run(
            ["bw", "encode"], input=json.dumps(data), capture_output=True, text=True, check=True
        ).stdout.strip()
        subprocess.run(
            ["bw", "edit", "item", data["id"], encoded],
            capture_output=True,
            text=True,
            check=True,
        )
        self._item_cache.pop(item, None)

    def item_exists(self, item: str) -> bool:
        try:
            self._item(item)
            return True
        except RuntimeError:
            return False


# --------------------------------------------------------------------------- #
# Backend selection
# --------------------------------------------------------------------------- #

_VAULT = os.environ.get("OP_VAULT", "raspi")
_BACKEND = os.environ.get("SECRET_BACKEND", "op")

if _BACKEND == "op":
    _b: Backend = OpBackend(_VAULT)
elif _BACKEND == "bw":
    _b = BwBackend(_VAULT)
else:
    raise RuntimeError(f"Unknown SECRET_BACKEND '{_BACKEND}' — expected 'op' or 'bw'")


def _get_or_create(item: str, field: str, gen) -> str:
    """Read a field, or generate + persist it on first call. Backs every
    auto-generated, must-survive-restarts secret (cookie/session/api keys)."""
    value = _b.read_field(item, field)
    if value:
        return value
    value = gen()
    _b.write_field(item, field, value)
    return value


# --------------------------------------------------------------------------- #
# Public helpers — vendor-neutral; task files call these
# --------------------------------------------------------------------------- #


def secret_field(item: str, field: str) -> str:
    """A single field from an item, or "". Used where a service maps an env var
    to a field name via `secret_env` in group_data/all.py (see HALO)."""
    return _b.read_field(item, field)


def save_field(item: str, field: str, value: str) -> None:
    """Upsert a concealed field. Used by post-deploy steps that persist a
    server-generated credential back to the store (e.g. Kanidm OIDC secrets)."""
    _b.write_field(item, field, value, concealed=True)


def pihole_password() -> str:
    return _b.read_login("pihole")["password"]


def cifs_creds(login: str) -> str:
    """`login` is a share's `creds` value from the CIFS dict — one of the two
    shared NAS accounts (`readonly` / `readwrite`)."""
    u = _b.read_field("cifs", f"{login}_username")
    p = _b.read_field("cifs", f"{login}_password")
    return f"username={u}\npassword={p}\n"


def reserve_creds() -> dict:
    """Login item `reserve`: username=email, password; plus the `api_base_url`
    field. Returns the RESERVE_* env the updater reads."""
    login = _b.read_login("reserve")
    return {
        "RESERVE_EMAIL": login["username"],
        "RESERVE_PASSWORD": login["password"],
        "RESERVE_API_BASE_URL": _b.read_field("reserve", "api_base_url"),
    }


def beszel_user_password(email: str) -> str:
    """Password for a managed beszel user (BESZEL["users"]); generated once and
    persisted as the `user_pw_<email>` field so it's stable + recoverable."""
    return _get_or_create("beszel", f"user_pw_{email}", lambda: secrets.token_urlsafe(32))


def cloudflare() -> dict:
    return {
        "token": _b.read_login("cloudflare")["password"],
        "zone_id": _b.read_field("cloudflare", "zone_id"),
    }


def netbird_server_secrets() -> dict:
    """Crypto material netbird-server needs at startup, generated on first deploy
    and persisted so it survives container recreation.

    - auth_secret: shared secret the embedded relay authenticates peers with.
    - encryption_key: at-rest encryption for the SQLite store. Losing it makes
      the store unreadable, so it must never be regenerated in place.
    - session_cookie_encryption_key: AES key for the embedded IdP (Dex) session
      cookies. NetBird wants 16/24/32 raw bytes; 32 hex chars is 32 bytes.
    """
    # Every field generates itself, but the *item* has to exist for `op item edit`
    # to have something to write to. NetBird is required-tier and this runs on the
    # very first deploy, so trade the backend's raw CalledProcessError for the one
    # command that fixes it.
    if not _b.item_exists("netbird"):
        raise RuntimeError(
            "vault: the 'netbird' item does not exist yet. Every field on it is "
            "generated by the deploy, so create it empty once:\n"
            f"    op item create --category login --title netbird --vault {_VAULT}\n"
            "then re-run the deploy."
        )
    return {
        "auth_secret": _get_or_create("netbird", "auth_secret", lambda: secrets.token_hex(32)),
        "encryption_key": _get_or_create(
            "netbird",
            "encryption_key",
            lambda: base64.b64encode(secrets.token_bytes(32)).decode(),
        ),
        "session_cookie_encryption_key": _get_or_create(
            "netbird", "session_cookie_encryption_key", lambda: secrets.token_hex(16)
        ),
    }


def netbird_bootstrap_owner_password() -> str:
    """Password for the one-time /api/setup owner. Only used while
    `setup_required` is true; afterwards NetBird owns the credential and this is
    just the recovery path for a local (non-Kanidm) login."""
    return _get_or_create("netbird", "bootstrap_owner_password", lambda: secrets.token_urlsafe(24))


def netbird_pat() -> str:
    """NetBird API token, or "" before /api/setup has minted one. Every
    declarative reconcile call authenticates with this."""
    return _b.read_field("netbird", "pat")


def save_netbird_pat(token: str) -> None:
    _b.write_field("netbird", "pat", token, concealed=True)


def netbird_setup_key(name: str) -> str:
    """A peer-enrolment setup key, or "" before the reconcile step created it.
    NetBird returns the plaintext key only in the POST response, so it is
    captured there and read back from here on later deploys."""
    return _b.read_field("netbird", f"setup_key_{name}")


def save_netbird_setup_key(name: str, key: str) -> None:
    _b.write_field("netbird", f"setup_key_{name}", key, concealed=True)


def vaultwarden_admin_token_hash() -> str:
    return _b.read_field("vaultwarden", "admin_token")


def vaultwarden_smtp_email() -> str:
    return _b.read_field("vaultwarden", "smtp_email")


def vaultwarden_smtp_password() -> str:
    return _b.read_field("vaultwarden", "smtp_password")


def asus_router_ssh() -> dict:
    return _b.read_ssh_key("asus-router")


def yarr_creds() -> dict:
    return _b.read_login("yarr")


def navidrome_creds() -> dict:
    return _b.read_login("navidrome")


def memos_creds() -> dict:
    return _b.read_login("memos")


def restic_password() -> str:
    return _b.read_login("restic")["password"]


def syncthing_creds() -> dict:
    return _b.read_login("syncthing")


def dockerhub_creds() -> dict:
    return _b.read_login("dockerhub")


def beszel_admin_creds() -> dict:
    """Hub admin email + password. Empty strings if the item is missing — hub
    comes up with no admin, set one in the web UI, populate the vault, redeploy."""
    if not _b.item_exists("beszel"):
        return {"email": "", "password": ""}
    login = _b.read_login("beszel")
    return {"email": login["username"], "password": login["password"]}


def kanidm_oidc_secret(field_name: str) -> str:
    """An OIDC client secret from the kanidm item, or "" before Kanidm has
    generated it on the first deploy."""
    return _b.read_field("kanidm", field_name)


def oauth2_proxy_cookie_secret() -> str:
    """Stable cookie secret (base64 of 32 random bytes) so sessions survive restarts."""
    return _get_or_create(
        "oauth2-proxy",
        "cookie_secret",
        lambda: base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip("="),
    )


def chat_session_key() -> str:
    """chat SESSION_KEY (64-byte hex) — stable so cookie-encrypted sessions survive restarts."""
    return _get_or_create("chat", "session_key", lambda: secrets.token_hex(64))


def chat_mcp_api_key() -> str:
    """Bearer for the mcp-chat -> chat-backend hop on /api/v1/*."""
    return _get_or_create("chat", "mcp_api_key", lambda: secrets.token_hex(32))


def chat_mcp_server_key() -> str:
    """Bearer that gates inbound clients hitting chat-mcp's /mcp."""
    return _get_or_create("chat", "mcp_server_key", lambda: secrets.token_hex(32))


def represent_session_key() -> str:
    """represent SESSION_KEY (64-byte hex) — the signed cookie is the entire
    auth credential, so the key must be stable across restarts."""
    return _get_or_create("represent", "session_key", lambda: secrets.token_hex(64))


def nib_session_key() -> str:
    """nib SESSION_KEY (64-byte hex) — signs the OIDC session cookie. nib refuses to
    boot without it, and changing it logs everyone out, so it must be stable."""
    return _get_or_create("nib", "session_key", lambda: secrets.token_hex(64))


def scribe_session_key() -> str:
    """scribe SESSION_KEY (64-byte hex) — stable so signed session cookies survive restarts."""
    return _get_or_create("scribe", "session_key", lambda: secrets.token_hex(64))


def scribe_press_token() -> str:
    """Bearer for the scribe -> scribe-press hop. Must match the mini's
    `mini/scribe-press` item `api_key` field — paste both sides identically."""
    return _b.read_field("scribe", "press_token")


def shelf_api_key() -> str:
    """Bearer for scribe-shelf (32-byte hex, auto). Lives on the `scribe` item
    (shelf is a scribe sidecar); shelf.env and scribe.env read the same value."""
    return _get_or_create("scribe", "shelf_api_key", lambda: secrets.token_hex(32))


def shim_passphrase() -> str:
    """Encrypts shim's on-disk Audible auth (48-byte hex, auto). Lives on the
    `scribe` item (shim is a scribe sidecar); stable across deploys."""
    return _get_or_create("scribe", "shim_passphrase", lambda: secrets.token_hex(48))
