"""Resolve mDNS-valued HOSTS aliases to live IPs, maintain /etc/hosts.

Each HOSTS entry whose value ends in `.local` is owned by this task:
- The script below runs `getent hosts <mdns>` and writes/updates the
  `<ip> <alias>` line in /etc/hosts.
- Triggered by a oneshot service that fires `OnBootSec=10s` and every 5
  minutes thereafter, so /etc/hosts stays in sync with whatever IP the
  router decides to hand out next.
- Other units (CIFS mounts, container quadlets) order themselves
  `After=hosts-discover.service` so they observe a populated /etc/hosts
  before they read it.

If HOSTS has no mDNS-valued entries, this task is a no-op.
"""

import io

from pyinfra.operations import files, server, systemd

from group_data.all import HOSTS

_mdns_aliases = {alias: target for alias, target in HOSTS.items() if target.endswith(".local")}

if _mdns_aliases:
    _lookups = "\n".join(f'resolve "{alias}" "{mdns}"' for alias, mdns in _mdns_aliases.items())
    _script = f"""\
#!/bin/bash
# Auto-generated by tasks/host_discover.py — do not edit by hand.
set -uo pipefail

HOSTS_FILE=/etc/hosts

resolve() {{
  local alias="$1" mdns="$2"
  local ip="" elapsed=0
  # At cold boot avahi hasn't finished its first network browse yet, so
  # mDNS lookups can return empty for the first ~10-30s. Block until we
  # get an answer (or hit the timeout) so dependent units — CIFS mount
  # in particular — observe a populated /etc/hosts before they run.
  while [ -z "$ip" ] && [ "$elapsed" -lt 30 ]; do
    ip=$(getent hosts "$mdns" 2>/dev/null | awk '{{print $1; exit}}')
    if [ -z "$ip" ]; then
      sleep 2
      elapsed=$((elapsed + 2))
    fi
  done
  if [ -z "$ip" ]; then
    echo "hosts-discover: mDNS lookup failed for $mdns (alias $alias) after 30s" >&2
    return 0
  fi
  local line="$ip $alias"
  if grep -qE "^[[:space:]]*[0-9.]+[[:space:]]+$alias([[:space:]]|$)" "$HOSTS_FILE"; then
    if ! grep -qE "^$ip[[:space:]]+$alias([[:space:]]|$)" "$HOSTS_FILE"; then
      sed -i -E "s|^[[:space:]]*[0-9.]+[[:space:]]+$alias([[:space:]]|$).*|$line|" "$HOSTS_FILE"
      echo "hosts-discover: $alias -> $ip"
    fi
  else
    echo "$line" >> "$HOSTS_FILE"
    echo "hosts-discover: $alias -> $ip (added)"
  fi
}}

{_lookups}
"""

    _service_unit = """\
[Unit]
Description=Resolve mDNS HOSTS aliases into /etc/hosts
After=avahi-daemon.service network-online.target
Wants=avahi-daemon.service network-online.target
Before=remote-fs.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/hosts-discover.sh
# Cover the worst-case 30s mDNS wait per alias plus avahi startup slack.
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
"""

    _timer_unit = """\
[Unit]
Description=Periodic mDNS -> /etc/hosts refresh

[Timer]
OnBootSec=10s
OnUnitActiveSec=5min
AccuracySec=10s

[Install]
WantedBy=timers.target
"""

    files.put(
        name="Write hosts-discover.sh",
        src=io.BytesIO(_script.encode()),
        dest="/usr/local/sbin/hosts-discover.sh",
        user="root",
        group="root",
        mode="755",
    )

    files.put(
        name="Write hosts-discover.service",
        src=io.BytesIO(_service_unit.encode()),
        dest="/etc/systemd/system/hosts-discover.service",
        user="root",
        group="root",
        mode="644",
    )

    files.put(
        name="Write hosts-discover.timer",
        src=io.BytesIO(_timer_unit.encode()),
        dest="/etc/systemd/system/hosts-discover.timer",
        user="root",
        group="root",
        mode="644",
    )

    systemd.service(
        name="Enable hosts-discover.timer",
        service="hosts-discover.timer",
        enabled=True,
        running=True,
        daemon_reload=True,
    )

    # Populate /etc/hosts now so downstream tasks (cifs, gatus) read a
    # current alias on first deploy rather than waiting for the timer.
    server.shell(
        name="Run hosts-discover once",
        commands=["systemctl start hosts-discover.service"],
    )
