"""Kanidm: identity management server (Podman Quadlet)."""

import hashlib
import io

from pyinfra.operations import files, server, systemd

from group_data.all import KANIDM, NETWORK
from tasks.util import resolve_latest, restart_if_changed

DOMAIN = NETWORK["domain"]

_image = (
    resolve_latest("kanidm/server", KANIDM["image"])
    if KANIDM.get("resolve_latest")
    else KANIDM["image"]
)

# Reads /etc/traefik/acme.json and writes the wildcard cert to
# /etc/kanidm/certs/{chain,key}.pem so Kanidm can serve TLS.
# A systemd path unit re-triggers this on every cert renewal.
_cert_sync_script = """\
#!/usr/bin/env python3
import base64, json, os, sys

ACME = "/etc/traefik/acme.json"
CERT_DIR = "/etc/kanidm/certs"

try:
    with open(ACME) as f:
        raw = f.read()
    if not raw.strip():
        print("acme.json is empty — Traefik has not issued a cert yet", file=sys.stderr)
        sys.exit(0)
    acme = json.loads(raw)
except FileNotFoundError:
    print(f"{ACME} not found", file=sys.stderr)
    sys.exit(0)

for resolver in acme.values():
    if not isinstance(resolver, dict):
        continue
    for cert in resolver.get("Certificates", []):
        if any("*" in s for s in cert.get("domain", {}).get("sans", [])):
            os.makedirs(CERT_DIR, exist_ok=True)
            chain_path = os.path.join(CERT_DIR, "chain.pem")
            key_path = os.path.join(CERT_DIR, "key.pem")
            with open(chain_path, "w") as f:
                f.write(base64.b64decode(cert["certificate"]).decode())
            with open(key_path, "w") as f:
                f.write(base64.b64decode(cert["key"]).decode())
            os.chmod(key_path, 0o600)
            print(f"kanidm-cert-sync: wrote wildcard cert to {CERT_DIR}")
            sys.exit(0)

print("kanidm-cert-sync: no wildcard cert found in acme.json", file=sys.stderr)
sys.exit(1)
"""

_cert_sync_service = """\
[Unit]
Description=Sync Traefik ACME wildcard cert to /etc/kanidm/certs
After=traefik.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/kanidm-cert-sync
"""

_cert_sync_path = """\
[Unit]
Description=Watch acme.json and re-sync kanidm certs on renewal

[Path]
PathChanged=/etc/traefik/acme.json

[Install]
WantedBy=multi-user.target
"""

# CLI client config — kept on disk in case it's ever needed for ad-hoc
# `podman exec kanidm /sbin/kanidm ...` debugging. kanidm_oidc.py talks to the
# REST API directly because the distroless image has no `kanidm` CLI binary.
_client_config = f"""\
uri = "https://idm.{DOMAIN}"
verify_ca = true
verify_hostnames = true
"""

# No EnvironmentFile — the admin password is injected one-shot during bootstrap
# (see below). All other config lives in Environment= directives.
quadlet = f"""\
[Unit]
Description=Kanidm identity management
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=kanidm
Image={_image}
Network=host
Volume=/var/lib/kanidm:/data
Volume=/etc/kanidm:/etc/kanidm:ro
Environment=KANIDM_ORIGIN=https://idm.{DOMAIN}
Environment=KANIDM_DOMAIN=idm.{DOMAIN}
Environment=KANIDM_DB_PATH=/data/kanidm.db
Environment=KANIDM_TLS_CHAIN=/etc/kanidm/certs/chain.pem
Environment=KANIDM_TLS_KEY=/etc/kanidm/certs/key.pem
Environment=KANIDM_BINDADDRESS={KANIDM["host"]}:{KANIDM["port"]}

[Service]
Restart=always
RestartSec=10
MemoryMax=128M

[Install]
WantedBy=multi-user.target
"""

_quadlet_hash = hashlib.sha256(quadlet.encode()).hexdigest()

# --- Cert sync infrastructure ---

files.put(
    name="Write kanidm-cert-sync script",
    src=io.BytesIO(_cert_sync_script.encode()),
    dest="/usr/local/bin/kanidm-cert-sync",
    user="root",
    group="root",
    mode="755",
)

files.put(
    name="Write kanidm-cert-sync.service",
    src=io.BytesIO(_cert_sync_service.encode()),
    dest="/etc/systemd/system/kanidm-cert-sync.service",
    user="root",
    group="root",
    mode="644",
)

files.put(
    name="Write kanidm-cert-sync.path",
    src=io.BytesIO(_cert_sync_path.encode()),
    dest="/etc/systemd/system/kanidm-cert-sync.path",
    user="root",
    group="root",
    mode="644",
)

systemd.service(
    name="Enable kanidm-cert-sync.path",
    service="kanidm-cert-sync.path",
    enabled=True,
    daemon_reload=True,
)

server.shell(
    name="Run initial cert sync",
    commands=["systemctl start kanidm-cert-sync.service || true"],
)

# --- Directories and static config ---
# Admin/idm_admin passwords are generated on-Pi by `kanidmd recover-account`
# (see bootstrap block below) and written to /etc/secrets/kanidm-{admin,idm_admin}-password.
# OIDC client secrets are generated by Kanidm and saved to Bitwarden by kanidm_oidc.py.

files.directory(
    name="Create /etc/kanidm",
    path="/etc/kanidm",
    user="root",
    group="root",
    mode="755",
    present=True,
)

files.directory(
    name="Create /var/lib/kanidm",
    path="/var/lib/kanidm",
    user="root",
    group="root",
    mode="700",
    present=True,
)

files.put(
    name="Write kanidm client config",
    src=io.BytesIO(_client_config.encode()),
    dest="/etc/kanidm/config",
    user="root",
    group="root",
    mode="644",
)

# --- Quadlet ---

files.put(
    name="Write kanidm.container quadlet",
    src=io.BytesIO(quadlet.encode()),
    dest="/etc/containers/systemd/kanidm.container",
    user="root",
    group="root",
    mode="644",
)

server.shell(
    name="Reload quadlet units",
    commands=[
        "/usr/lib/systemd/system-generators/podman-system-generator /run/systemd/generator 2>/dev/null || true",
    ],
)

# --- Start / restart ---

systemd.service(
    name="Start kanidm",
    service="kanidm",
    running=True,
    daemon_reload=True,
)

server.shell(
    name="Restart kanidm if quadlet changed",
    commands=[restart_if_changed("kanidm", _quadlet_hash)],
)

# --- Bootstrap admin passwords (one-shot) ---
# The server image is distroless but includes kanidmd which has a
# `recover-account` subcommand that resets a password and prints the new one.
# We recover both `admin` (system config) and `idm_admin` (identity/OAuth2
# management). kanidm_oidc.py uses idm_admin for person + OIDC setup.

_bootstrap_script = f"""
# Wait for kanidm to be ready (DB must exist)
for i in $(seq 1 30); do
    curl -sf -k https://127.0.0.1:{KANIDM["port"]}/status >/dev/null 2>&1 && break
    sleep 2
done

NEED_RESTART=0
for ACCOUNT in admin idm_admin; do
    STAMP=/var/lib/kanidm/.${{ACCOUNT}}-bootstrapped
    PASSFILE=/etc/secrets/kanidm-${{ACCOUNT}}-password
    if [ -f "$STAMP" ] && [ -f "$PASSFILE" ]; then
        echo "kanidm: $ACCOUNT already bootstrapped"
        continue
    fi

    NEW_PASS=$(podman exec kanidm /sbin/kanidmd recover-account "$ACCOUNT" 2>&1 \\
        | grep 'new_password:' | sed 's/.*new_password: "\\(.*\\)"/\\1/')

    if [ -z "$NEW_PASS" ]; then
        echo "kanidm: failed to recover $ACCOUNT password" >&2
        exit 1
    fi

    printf '%s' "$NEW_PASS" > "$PASSFILE"
    chmod 600 "$PASSFILE"
    touch "$STAMP"
    echo "kanidm: $ACCOUNT password recovered and saved"
    NEED_RESTART=1
done

# recover-account opens the DB while the server is running; restart to ensure
# the server picks up the changes cleanly.
if [ "$NEED_RESTART" = "1" ]; then
    systemctl restart kanidm
    echo "kanidm: restarted after bootstrap"
fi
"""

server.shell(
    name="Bootstrap kanidm admin passwords (first boot only)",
    commands=[_bootstrap_script],
)
