"""Kanidm OIDC integration: create person accounts and configure OAuth2 clients.

Assumes kanidm is running and healthy. Safe to re-run — all steps are idempotent.
Driven by KANIDM_PERSONS and KANIDM_OIDC_CLIENTS in group_data/all.py.

Uses the Kanidm REST API directly (the server image is distroless and has no
CLI binary; the CLI requires a TTY for password input and cannot be automated).
Authenticates as idm_admin (not admin — only idm_admin can manage persons and
OAuth2 clients).

OIDC client secrets are generated by Kanidm (cannot be set externally). On first
deploy the secret is read from the API and saved to Bitwarden. Subsequent deploys
read it from BW via secrets.py. A second deploy (or targeted
`tasks/secrets.py tasks/vaultwarden.py`) is needed after first setup to
propagate the generated secret to downstream services.
"""

import json
import subprocess

from pyinfra import logger
from pyinfra.operations import python, server

import vault as bw
from group_data.all import KANIDM, KANIDM_OIDC_CLIENTS, KANIDM_PERSONS, NETWORK

DOMAIN = NETWORK["domain"]

# Serialize config for the embedded Python script on the Pi
_persons_json = json.dumps(KANIDM_PERSONS)
_clients_json = json.dumps(
    {
        name: {
            "display_name": cfg["display_name"],
            "origin": f"https://{cfg['url_prefix']}.{DOMAIN}",
            "redirect": f"https://{cfg['url_prefix']}.{DOMAIN}{cfg['redirect_path']}",
            "scopes": cfg["scopes"],
            "disable_pkce": cfg.get("disable_pkce", False),
        }
        for name, cfg in KANIDM_OIDC_CLIENTS.items()
    }
)

server.shell(
    name="Create Kanidm persons and configure OIDC clients",
    commands=[
        f"""
        # Wait up to 60 s for Kanidm to be ready
        for i in $(seq 1 30); do
          curl -sf -k https://127.0.0.1:{KANIDM["port"]}/status >/dev/null 2>&1 && break
          sleep 2
        done
        if ! curl -sf -k https://127.0.0.1:{KANIDM["port"]}/status >/dev/null 2>&1; then
          echo "kanidm: server not ready after 60 s — skipping setup" >&2
          exit 0
        fi

        IDM_PASS=$(cat /etc/secrets/kanidm-idm_admin-password 2>/dev/null)
        if [ -z "$IDM_PASS" ]; then
          echo "kanidm: idm_admin password not found — run kanidm.py first" >&2
          exit 0
        fi

        export __KDM_PASS="$IDM_PASS"

        python3 << 'PYEOF'
import json, os, ssl, sys
from http.cookiejar import CookieJar
from urllib.request import Request, build_opener, HTTPCookieProcessor, HTTPSHandler
from urllib.error import HTTPError

BASE = "https://127.0.0.1:{KANIDM["port"]}"
ORIGIN = "https://idm.{DOMAIN}"
ctx = ssl._create_unverified_context()
cj = CookieJar()
opener = build_opener(HTTPSHandler(context=ctx), HTTPCookieProcessor(cj))

def api(method, path, data=None, token=None):
    headers = {{"Content-Type": "application/json"}}
    if token:
        headers["Authorization"] = f"Bearer {{token}}"
    body = json.dumps(data).encode() if data is not None else None
    req = Request(BASE + path, data=body, headers=headers, method=method)
    resp = opener.open(req)
    raw = resp.read()
    return json.loads(raw) if raw.strip() else {{}}

def exists(path, token):
    try:
        result = api("GET", path, token=token)
        return result is not None and result != {{}}
    except HTTPError as e:
        if e.code == 404:
            return False
        raise

# --- Authenticate as idm_admin (3-step flow: init -> begin -> cred) ---
pw = os.environ["__KDM_PASS"]
try:
    api("POST", "/v1/auth", {{"step": {{"init": "idm_admin"}}}})
    api("POST", "/v1/auth", {{"step": {{"begin": "password"}}}})
    r = api("POST", "/v1/auth", {{"step": {{"cred": {{"password": pw}}}}}})
    token = r["state"]["success"]
except Exception as e:
    print(f"kanidm: idm_admin auth failed: {{e}}", file=sys.stderr)
    sys.exit(0)

print("kanidm: idm_admin authenticated")

# --- Create persons ---
persons = json.loads({_persons_json!r})
for username, info in persons.items():
    if not exists(f"/v1/person/{{username}}", token):
        api("POST", "/v1/person", {{
            "attrs": {{
                "name": [username],
                "displayname": [info["display_name"]],
            }}
        }}, token=token)
        print(f"kanidm: person {{username}} created")
    else:
        print(f"kanidm: person {{username}} already exists")

    # Always sync displayname and mail (handles config changes)
    api("PATCH", f"/v1/person/{{username}}", {{
        "attrs": {{
            "displayname": [info["display_name"]],
            "mail": [info["email"]],
        }}
    }}, token=token)

    # Generate credential reset token (one-shot per person)
    stamp = f"/var/lib/kanidm/.person-{{username}}-setup"
    if not os.path.exists(stamp):
        try:
            r = api("GET", f"/v1/person/{{username}}/_credential/_update_intent", token=token)
            tok = r.get("token", "")
            if tok:
                url = f"{{ORIGIN}}/ui/reset?token={{tok}}"
                with open(f"/var/lib/kanidm/.reset-token-{{username}}", "w") as f:
                    f.write(url)
                open(stamp, "w").close()
                print(f"kanidm: reset token for {{username}}: {{url}}")
        except Exception as e:
            print(f"kanidm: failed to get reset token for {{username}}: {{e}}")

# --- Configure OAuth2 clients ---
clients = json.loads({_clients_json!r})

for name, cfg in clients.items():
    if not exists(f"/v1/oauth2/{{name}}", token):
        api("POST", "/v1/oauth2/_basic", {{
            "attrs": {{
                "name": [name],
                "displayname": [cfg["display_name"]],
                "oauth2_rs_origin_landing": [cfg["origin"]],
                "oauth2_rs_origin": [cfg["redirect"]],
            }}
        }}, token=token)
        print(f"kanidm: oauth2 {{name}} created")
    else:
        # Update redirect URL via PATCH (idempotent)
        api("PATCH", f"/v1/oauth2/{{name}}", {{
            "attrs": {{"oauth2_rs_origin": [cfg["redirect"]]}}
        }}, token=token)
        print(f"kanidm: oauth2 {{name}} already exists, redirect updated")

    # Set scope map for all persons (idempotent)
    api("POST", f"/v1/oauth2/{{name}}/_scopemap/idm_all_persons",
        cfg["scopes"], token=token)

    # Disable PKCE for clients that don't support it (idempotent)
    if cfg.get("disable_pkce"):
        api("PATCH", f"/v1/oauth2/{{name}}", {{
            "attrs": {{"oauth2_allow_insecure_client_disable_pkce": ["true"]}}
        }}, token=token)
        print(f"kanidm: oauth2 {{name}} PKCE disabled")

    # Read the Kanidm-generated client secret and save to a temp file
    # so _save_to_bitwarden can pick it up
    try:
        secret = api("GET", f"/v1/oauth2/{{name}}/_basic_secret", token=token)
        if secret:
            with open(f"/var/lib/kanidm/.oidc-secret-{{name}}", "w") as f:
                f.write(secret if isinstance(secret, str) else json.dumps(secret))
            print(f"kanidm: oauth2 {{name}} secret saved to temp file")
    except HTTPError as e:
        print(f"kanidm: could not read {{name}} secret: {{e}}")

    print(f"kanidm: oauth2 {{name}} configured")

PYEOF
        unset __KDM_PASS
        """,
    ],
)

# --- Save credentials to Bitwarden (runs locally) ---


def _ssh_cat(path):
    """Read a file from the Pi via SSH, return contents or empty string."""
    r = subprocess.run(
        ["ssh", "raspi", f"sudo cat {path} 2>/dev/null"],
        capture_output=True,
        text=True,
    )
    return r.stdout.strip()


def _save_to_bitwarden(state=None, host=None):
    # Batch all changes to the kanidm BW item into a single edit to avoid
    # revision conflicts from multiple rapid edits.
    item = json.loads(json.dumps(bw._get_item("kanidm")))  # copy
    changed = False

    fields = item.get("fields") or []

    # Admin + idm_admin passwords (both recovered on first boot)
    for account, field_name in [
        ("admin", "admin_password"),
        ("idm_admin", "idm_admin_password"),
    ]:
        password = _ssh_cat(f"/etc/secrets/kanidm-{account}-password")
        if not password:
            continue
        existing = next((f for f in fields if f["name"] == field_name), None)
        if existing:
            if existing["value"] != password:
                existing["value"] = password
                changed = True
                logger.info(f"kanidm: {field_name} updated in Bitwarden")
        else:
            fields.append({"name": field_name, "value": password, "type": 1})
            changed = True
            logger.info(f"kanidm: {field_name} saved to Bitwarden")

    # OIDC client secrets (generated by Kanidm, read from API)
    for client_name, cfg in KANIDM_OIDC_CLIENTS.items():
        secret = _ssh_cat(f"/var/lib/kanidm/.oidc-secret-{client_name}").strip('"')
        if not secret:
            continue
        field_name = cfg["secret_field"]
        existing = next((f for f in fields if f["name"] == field_name), None)
        if existing:
            if existing["value"] != secret:
                existing["value"] = secret
                changed = True
                logger.info(f"kanidm: {client_name} OIDC secret updated in Bitwarden")
        else:
            fields.append({"name": field_name, "value": secret, "type": 1})
            changed = True
            logger.info(f"kanidm: {client_name} OIDC secret saved to Bitwarden")

    # Per-person reset tokens
    for username in KANIDM_PERSONS:
        token = _ssh_cat(f"/var/lib/kanidm/.reset-token-{username}")
        if not token:
            continue

        logger.info(f"kanidm: credential reset token for {username}:\n{token}")

        field_name = f"{username}_reset_token"
        existing = next((f for f in fields if f["name"] == field_name), None)
        if existing:
            if not existing["value"]:
                existing["value"] = token
                changed = True
                logger.info(f"kanidm: saved {username} reset token to Bitwarden")
        else:
            fields.append({"name": field_name, "value": token, "type": 1})
            changed = True
            logger.info(f"kanidm: saved {username} reset token to Bitwarden")

        # Clean up temp file
        subprocess.run(
            ["ssh", "raspi", f"sudo rm -f /var/lib/kanidm/.reset-token-{username}"],
            capture_output=True,
        )

    if changed:
        item["fields"] = fields
        bw._edit_item(item)
        logger.info("kanidm: Bitwarden item updated")


python.call(
    name="Save Kanidm credentials to Bitwarden",
    function=_save_to_bitwarden,
)
