"""Write secrets from Bitwarden to /etc/secrets/ on the Pi.

Per-service secret files are gated two ways: on the service's dict (commenting
it in group_data/all.py stops its env file being written) AND on the host's
feature set — this task is in the `base` bundle so it runs on every host, but a
camera node (raspo) must not fetch BW items or drop plaintext for services it
doesn't run. Each block below is therefore wrapped in a `feature(...)` guard;
on the full server (raspi) every guard is true, so output is unchanged.
"""

import io

from pyinfra.operations import files

import vault
from group_data.all import CIFS, KANIDM_OIDC_CLIENTS, NETWORK
from tasks.util import feature, optional

RESTIC = optional("RESTIC")
HALO = optional("HALO")
RESERVE = optional("RESERVE")
VAULTWARDEN = optional("VAULTWARDEN")
MEMOS = optional("MEMOS")
CHAT = optional("CHAT")
MCP_CHAT = optional("MCP_CHAT")
REPRESENT = optional("REPRESENT")
SCRIBE = optional("SCRIBE")
SHIM = optional("SHIM")
SHELF = optional("SHELF")
RASPI_DASHBOARD = optional("RASPI_DASHBOARD")

DOMAIN = NETWORK["domain"]


def _put_secret(name, content, dest, mode="600", group="root"):
    files.put(
        name=f"Write secret: {name}",
        src=io.BytesIO(content.encode()),
        dest=dest,
        user="root",
        group=group,
        mode=mode,
    )


# --- CIFS (NAS mounts) — `storage` feature ---

if feature("storage"):
    for _name in CIFS:
        # A share may borrow another's vault credentials via a "creds" alias
        # (e.g. mods reuses music's login) instead of its own *_username/
        # *_password fields. Defaults to the share's own name.
        _creds_key = CIFS[_name].get("creds", _name)
        _put_secret(f"cifs-{_name}", vault.cifs_creds(_creds_key), f"/etc/secrets/cifs-{_name}")

# --- Cloudflare API token — used by traefik's DNS-01 challenge (`proxy`) and
# the DNS record management in tasks/cloudflare_dns.py (`dns`). ---

if feature("proxy") or feature("dns"):
    cf = vault.cloudflare()
    _put_secret(
        "cloudflare.env",
        f"CF_DNS_API_TOKEN={cf['token']}\nzone_id={cf['zone_id']}\n",
        "/etc/secrets/cloudflare.env",
        mode="640",
        group="traefik",
    )

# --- oauth2-proxy (`sso`) ---
# Skipped on first deploy until kanidm_oidc.py has generated the client secret.

if feature("sso"):
    _op_oidc = KANIDM_OIDC_CLIENTS.get("oauth2-proxy")
    _op_client_secret = vault.kanidm_oidc_secret(_op_oidc["secret_field"]) if _op_oidc else ""
    if _op_client_secret:
        _put_secret(
            "oauth2-proxy.env",
            f"OAUTH2_PROXY_CLIENT_SECRET={_op_client_secret}\n"
            f"OAUTH2_PROXY_COOKIE_SECRET={vault.oauth2_proxy_cookie_secret()}\n",
            "/etc/secrets/oauth2-proxy.env",
        )

# --- Halo ---

if feature("apps") and HALO:
    _halo_secret_lines = [
        f"{var}={vault.secret_field('halo', field)}" for var, field in HALO["secret_env"].items()
    ]
    _put_secret("halo.env", "\n".join(_halo_secret_lines) + "\n", "/etc/secrets/halo.env")

if feature("apps") and RESERVE:
    _reserve_lines = [f"{k}={v}" for k, v in vault.reserve_creds().items()]
    _put_secret("reserve.env", "\n".join(_reserve_lines) + "\n", "/etc/secrets/reserve.env")

# --- Vaultwarden ---
# Kanidm admin/idm_admin passwords are generated on-Pi by `kanidmd recover-account`
# (see kanidm.py). OIDC client secrets are generated by Kanidm and saved to BW
# by kanidm_oidc.py — read here on subsequent deploys.

if feature("apps") and VAULTWARDEN:
    _vw_lines = [
        f"ADMIN_TOKEN={vault.vaultwarden_admin_token_hash()}",
        "SIGNUPS_ALLOWED=true",
        "SMTP_HOST=smtp.gmail.com",
        "SMTP_PORT=587",
        "SMTP_SECURITY=starttls",
        f"SMTP_USERNAME={vault.vaultwarden_smtp_email()}",
        f"SMTP_FROM={vault.vaultwarden_smtp_email()}",
        f"SMTP_PASSWORD={vault.vaultwarden_smtp_password()}",
    ]

    # OIDC is optional — Vaultwarden runs without SSO if not in KANIDM_OIDC_CLIENTS
    # or until Kanidm has generated the client secret on a previous deploy.
    _vw_oidc = KANIDM_OIDC_CLIENTS.get("vaultwarden")
    _vw_oidc_secret = vault.kanidm_oidc_secret(_vw_oidc["secret_field"]) if _vw_oidc else ""
    if _vw_oidc_secret:
        _vw_lines.extend(
            [
                "SSO_ENABLED=true",
                "SSO_ONLY=false",
                "SSO_SIGNUPS_MATCH_EMAIL=true",
                f"SSO_AUTHORITY=https://idm.{DOMAIN}/oauth2/openid/vaultwarden",
                "SSO_CLIENT_ID=vaultwarden",
                f"SSO_CLIENT_SECRET={_vw_oidc_secret}",
            ]
        )

    _put_secret(
        "vaultwarden.env",
        "\n".join(_vw_lines) + "\n",
        "/etc/secrets/vaultwarden.env",
    )

# --- Memos ---
# Bootstrap admin (HOST) user creds. Sourced by tasks/memos.py to seed the
# first user via the Memos REST API and to authenticate the Kanidm IdP
# registration that follows.

if feature("apps") and MEMOS:
    _memos_creds = vault.memos_creds()
    _memos_pw = _memos_creds["password"].replace("'", "'\\''")
    _memos_oidc = KANIDM_OIDC_CLIENTS.get("memos")
    _memos_oidc_secret = (
        vault.kanidm_oidc_secret(_memos_oidc["secret_field"]) if _memos_oidc else ""
    )
    _memos_lines = [
        f"MEMOS_USERNAME={_memos_creds['username']}",
        f"MEMOS_PASSWORD='{_memos_pw}'",
    ]
    if _memos_oidc_secret:
        _memos_lines.append(f"MEMOS_OIDC_CLIENT_SECRET='{_memos_oidc_secret}'")
    _put_secret("memos.env", "\n".join(_memos_lines) + "\n", "/etc/secrets/memos.env")

# --- Chat + chat-mcp ---
# CHAT_MCP_API_KEY is shared: chat gates /api/v1/* against unauthenticated
# callers, mcp-chat sends the same value as Bearer on every hop. Fetch it once
# when either side is deployed.

if feature("chat") and (CHAT or MCP_CHAT):
    _chat_mcp_api_key = vault.chat_mcp_api_key()

if feature("chat") and CHAT:
    # SESSION_KEY is auto-generated on first deploy. OIDC vars are written only
    # once Kanidm has produced the client secret on a previous deploy.
    _chat_oidc = KANIDM_OIDC_CLIENTS.get("chat")
    _chat_oidc_secret = vault.kanidm_oidc_secret(_chat_oidc["secret_field"]) if _chat_oidc else ""
    _chat_lines = [
        f"SESSION_KEY={vault.chat_session_key()}",
        f"CHAT_MCP_API_KEY={_chat_mcp_api_key}",
    ]
    if _chat_oidc_secret:
        _chat_lines.extend(
            [
                f"OIDC_ISSUER=https://idm.{DOMAIN}/oauth2/openid/chat",
                "OIDC_CLIENT_ID=chat",
                f"OIDC_CLIENT_SECRET={_chat_oidc_secret}",
                f"OIDC_REDIRECT_URL=https://chat.{DOMAIN}/auth/callback",
            ]
        )
    _put_secret("chat.env", "\n".join(_chat_lines) + "\n", "/etc/secrets/chat.env")

if feature("chat") and MCP_CHAT:
    # Forwards CHAT_MCP_API_KEY to the chat backend hop and gates inbound /mcp
    # clients with CHAT_MCP_SERVER_KEY. Both are auto-generated in BW.
    _put_secret(
        "mcp-chat.env",
        f"CHAT_MCP_API_KEY={_chat_mcp_api_key}\nCHAT_MCP_SERVER_KEY={vault.chat_mcp_server_key()}\n",
        "/etc/secrets/mcp-chat.env",
    )

# --- Represent ---
# Same pattern as chat. SESSION_KEY is auto-generated on first deploy; OIDC
# vars are written only once Kanidm has produced the client secret on a
# previous deploy (until then represent runs on forward-auth headers only).

if feature("apps") and REPRESENT:
    _rep_oidc = KANIDM_OIDC_CLIENTS.get("represent")
    _rep_oidc_secret = vault.kanidm_oidc_secret(_rep_oidc["secret_field"]) if _rep_oidc else ""
    _rep_lines = [f"SESSION_KEY={vault.represent_session_key()}"]
    if _rep_oidc_secret:
        _rep_lines.extend(
            [
                f"OIDC_ISSUER=https://idm.{DOMAIN}/oauth2/openid/represent",
                "OIDC_CLIENT_ID=represent",
                f"OIDC_CLIENT_SECRET={_rep_oidc_secret}",
                f"OIDC_REDIRECT_URL=https://represent.{DOMAIN}/auth/callback",
            ]
        )
    _put_secret("represent.env", "\n".join(_rep_lines) + "\n", "/etc/secrets/represent.env")

# --- Scribe ---
# Same pattern as chat. OIDC vars are written only once Kanidm has produced
# the client secret on a previous deploy. press_token + abs_token are
# hand-pasted on the `scribe` BW item (deploy raises if either is empty).

if feature("scribe") and SCRIBE:
    _scribe_oidc = KANIDM_OIDC_CLIENTS.get("scribe")
    _scribe_oidc_secret = (
        vault.kanidm_oidc_secret(_scribe_oidc["secret_field"]) if _scribe_oidc else ""
    )
    _scribe_lines = [
        f"SESSION_KEY={vault.scribe_session_key()}",
        f"SCRIBE_PRESS_TOKEN={vault.scribe_press_token()}",
        f"ABS_TOKEN={vault.scribe_abs_token()}",
        # Same value as /etc/secrets/shelf.env — paired so scribe's UI
        # can surface the key without an extra service round-trip.
        f"SCRIBE_SHELF_API_KEY={vault.shelf_api_key()}",
    ]
    if _scribe_oidc_secret:
        _scribe_lines.extend(
            [
                f"OIDC_ISSUER=https://idm.{DOMAIN}/oauth2/openid/scribe",
                "OIDC_CLIENT_ID=scribe",
                f"OIDC_CLIENT_SECRET={_scribe_oidc_secret}",
                f"OIDC_REDIRECT_URL=https://scribe.{DOMAIN}/auth/callback",
            ]
        )
    _put_secret("scribe.env", "\n".join(_scribe_lines) + "\n", "/etc/secrets/scribe.env")

# --- Shim (Audible sidecar) ---
# Single encryption passphrase used for ALL on-disk account files.
# Auto-generated on first deploy and persisted to BW so it survives restarts.

if feature("scribe") and SHIM:
    _put_secret(
        "shim.env",
        f"SHIM_PASSPHRASE={vault.shim_passphrase()}\n",
        "/etc/secrets/shim.env",
    )

# --- Shelf (optional ABS-compat sidecar) ---
# Bearer key lives on the `scribe` BW item as `shelf_api_key` — shelf
# is a scribe sidecar so the credential follows its owner. scribe.env
# above pipes the same value through SCRIBE_SHELF_API_KEY so /api/me
# can surface it to logged-in users.

if feature("scribe") and SHELF:
    _put_secret(
        "shelf.env",
        f"SHELF_API_KEY={vault.shelf_api_key()}\n",
        "/etc/secrets/shelf.env",
    )

# --- raspi-dashboard ---
# Read-only beszel creds for the user declared in BESZEL["users"]. The password
# is generated once + stored on the `beszel` BW item (vault.beszel_user_password);
# tasks/beszel.py provisions the matching PocketBase user. The file is always
# written (the quadlet's EnvironmentFile requires it to exist).
if feature("monitoring") and RASPI_DASHBOARD:
    _dash_email = RASPI_DASHBOARD["beszel_user"]
    _put_secret(
        "raspi-dashboard.env",
        f"BESZEL_USER={_dash_email}\nBESZEL_PASSWORD={vault.beszel_user_password(_dash_email)}\n",
        "/etc/secrets/raspi-dashboard.env",
    )

# --- restic ---
# Sourced by /usr/local/sbin/raspi-backup; password may contain special chars
# so single-quote-escape it for `source` to handle correctly.
if feature("backup") and RESTIC is not None and CIFS.get("backups"):
    _restic_pw = vault.restic_password().replace("'", "'\\''")
    _restic_repo = f"{CIFS['backups']['mountpoint']}/raspi-restic"
    _put_secret(
        "restic.env",
        f"RESTIC_PASSWORD='{_restic_pw}'\n"
        f"RESTIC_REPOSITORY='{_restic_repo}'\n"
        f"RESTIC_CACHE_DIR='/var/cache/restic'\n",
        "/etc/secrets/restic.env",
    )
