"""Write secrets from Bitwarden to /etc/secrets/ on the Pi."""

import io

from pyinfra.operations import files

import vault as bw
from group_data.all import CIFS, HCC, KANIDM_OIDC_CLIENTS, NETWORK

try:
    from group_data.all import RESTIC
except ImportError:
    RESTIC = None


def _put_secret(name, content, dest, mode="600", group="root"):
    files.put(
        name=f"Write secret: {name}",
        src=io.BytesIO(content.encode()),
        dest=dest,
        user="root",
        group=group,
        mode=mode,
    )


_hcc_secret_lines = [
    f"{var}={bw.bw_field('hcc', field)}" for var, field in HCC["secret_env"].items()
]
_put_secret("hcc.env", "\n".join(_hcc_secret_lines) + "\n", "/etc/secrets/hcc.env")

for _name in CIFS:
    _put_secret(f"cifs-{_name}", bw.cifs_creds(_name), f"/etc/secrets/cifs-{_name}")

cf = bw.cloudflare()
_put_secret(
    "cloudflare.env",
    f"CF_DNS_API_TOKEN={cf['token']}\nzone_id={cf['zone_id']}\n",
    "/etc/secrets/cloudflare.env",
    mode="640",
    group="traefik",
)

# --- Vaultwarden ---
# Kanidm admin/idm_admin passwords are generated on-Pi by `kanidmd recover-account`
# (see kanidm.py). OIDC client secrets are generated by Kanidm and saved to BW
# by kanidm_oidc.py — read here on subsequent deploys.

DOMAIN = NETWORK["domain"]

_vw_lines = [
    f"ADMIN_TOKEN={bw.vaultwarden_admin_token_hash()}",
    "SIGNUPS_ALLOWED=true",
    "SMTP_HOST=smtp.gmail.com",
    "SMTP_PORT=587",
    "SMTP_SECURITY=starttls",
    f"SMTP_USERNAME={bw.vaultwarden_smtp_email()}",
    f"SMTP_FROM={bw.vaultwarden_smtp_email()}",
    f"SMTP_PASSWORD={bw.vaultwarden_smtp_password()}",
]

# OIDC is optional — Vaultwarden runs without SSO if not in KANIDM_OIDC_CLIENTS
# or until Kanidm has generated the client secret on a previous deploy.
_vw_oidc = KANIDM_OIDC_CLIENTS.get("vaultwarden")
_vw_oidc_secret = bw.kanidm_oidc_secret(_vw_oidc["secret_field"]) if _vw_oidc else ""
if _vw_oidc_secret:
    _vw_lines.extend(
        [
            "SSO_ENABLED=true",
            "SSO_ONLY=false",
            "SSO_SIGNUPS_MATCH_EMAIL=true",
            f"SSO_AUTHORITY=https://idm.{DOMAIN}/oauth2/openid/vaultwarden",
            "SSO_CLIENT_ID=vaultwarden",
            f"SSO_CLIENT_SECRET={_vw_oidc_secret}",
        ]
    )

_put_secret(
    "vaultwarden.env",
    "\n".join(_vw_lines) + "\n",
    "/etc/secrets/vaultwarden.env",
)

# --- oauth2-proxy ---
# Skipped on first deploy until kanidm_oidc.py has generated the client secret.

_op_oidc = KANIDM_OIDC_CLIENTS.get("oauth2-proxy")
_op_client_secret = bw.kanidm_oidc_secret(_op_oidc["secret_field"]) if _op_oidc else ""
if _op_client_secret:
    _put_secret(
        "oauth2-proxy.env",
        f"OAUTH2_PROXY_CLIENT_SECRET={_op_client_secret}\n"
        f"OAUTH2_PROXY_COOKIE_SECRET={bw.oauth2_proxy_cookie_secret()}\n",
        "/etc/secrets/oauth2-proxy.env",
    )

# --- restic ---
# Sourced by /usr/local/sbin/raspi-backup; password may contain special chars
# so single-quote-escape it for `source` to handle correctly.
if RESTIC is not None and CIFS.get("backups"):
    _restic_pw = bw.restic_password().replace("'", "'\\''")
    _restic_repo = f"{CIFS['backups']['mountpoint']}/raspi-restic"
    _put_secret(
        "restic.env",
        f"RESTIC_PASSWORD='{_restic_pw}'\n"
        f"RESTIC_REPOSITORY='{_restic_repo}'\n"
        f"RESTIC_CACHE_DIR='/var/cache/restic'\n",
        "/etc/secrets/restic.env",
    )
